### ISSUE TITLE
Support Squash Merge as valid Merge request commit

### ISSUE THREAD

**Issue by tmspicer** [jefflinse/pr-semver-bump#15]
Currently if you squash merge your PR the semver bump will fail, as it can't determine the merge request.
This is because it's looking at the merge request commit message to parse out the merge request.

The error you will receive is
```head commit doesn't look like a PR merge, skipping version bumping and tagging```

Squash merging of large PR's is a best practice and I would like to request this support be added.

**Comment by jefflinse** [comment]
Resolved with PR #16
